# Generated by Django 5.0.1 on 2024-03-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0003_remove_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
