# Generated by Django 5.0.1 on 2024-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0004_remove_choice_text_choice_option1_choice_option2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option4',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
